---
# tasks file for docker-ce
- name: Add Docker CE repository
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo
    checksum: "{{ docker_ce_repo_checksum }}"
    owner: root
    group: root
    mode: '0644'
    seuser: system_u
    serole: object_r
    setype: system_conf_t

- name: Remove older versions of Docker on EL7
  ansible.builtin.include_tasks: remove_old_docker_el7.yaml
  when: ansible_facts['distribution_major_version'] == '7'

- name: Remove older versions of Docker on >= EL8
  ansible.builtin.include_tasks: remove_old_docker_el8.yaml
  when: ansible_facts['distribution_major_version'] == '8'

- name: Install Docker CE Stable on EL7
  ansible.builtin.include_tasks: install_docker_el7.yaml
  when: ansible_facts['distribution_major_version'] == '7'

- name: Install Docker CE Stable on >= EL8
  ansible.builtin.include_tasks: install_docker_el8.yaml
  when: ansible_facts['distribution_major_version'] == '8'

- name: Start and Enable Docker services
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: yes
    state: started
  loop:
    - docker.service
    - containerd.service
