---
# Remove older versions of Docker
- name: Uninstall older versions of Docker
  ansible.builtin.yum:
    name:
      - docker
      - docker-client
      - docker-client-latest
      - docker-common
      - docker-latest
      - docker-latest-logrotate
      - docker-logrotate
      - docker-engine
    autoremove: yes
    state: absent
