galaxy_info:
  author: AlmaLinux OS Community
  description: Minimal configuration for ELevate
  company: AlmaLinux OS Foundation

  license: GPL-3.0-or-later

  min_ansible_version: 2.11

  platforms:
  - name: EL
    versions:
    - 7
    - 8
    - 9

  galaxy_tags:
    - elevate
    - upgrade
    - cleanup
    - el7
    - el8
    - el9
